## Create a new Ionic app

To set up the project, we'll first create a new Ionic app with the Ionic CLI. We'll then add Amplify and initialize a new project.

From your projects directory, run the following commands:

```bash
npm install -g ionic
ionic start myAmplifyProject blank --type=angular 
cd myAmplifyProject
npm start
```

This runs a development server and allows us to see the output generated by the build, you can see the running app by navigating to `localhost`.

## Initialize a new backend

Now that we have a running Ionic app, it's time to set up Amplify so that we can create the necessary backend services needed to support the app. From the root of the project, run:

```bash
amplify init
```

When you initialize Amplify you'll be prompted for some information about the app:

```console
Enter a name for the project (todo)

# All AWS services you provision for your app are grouped into an "environment"
# A common naming convention is dev, staging, and production
Enter a name for the environment (dev)

# Sometimes the CLI will prompt you to edit a file, it will use this editor to open those files.
Choose your default editor

# Amplify supports JavaScript (Web & React Native), iOS, and Android apps
Choose the type of app that you're building (javascript)

What JavaScript framework are you using (ionic)

Source directory path (src)

Distribution directory path (www)

Build command (npm run-script build)

Start command (ionic serve)

# This is the profile you created with the `amplify configure` command in the introduction step.
Do you want to use an AWS profile
```

When you initialize a new Amplify project, a few things happen:

- It creates a top level directory called `amplify` that stores your backend definition. During the tutorial you'll add capabilities such as authentication, GraphQL API, storage, and set up authorization rules for the API. As you add features, the `amplify` folder will grow with infrastructure-as-code templates that define your backend stack. Infrastructure-as-code is a best practice way to create a replicable backend stack.
- It creates a file called `aws-exports.js` in the `src` directory that holds all the configuration for the services you create with Amplify. This is how the Amplify client is able to get the necessary information about your backend services.
- It modifies the `.gitignore` file, adding some generated files to the ignore list
- A cloud project is created for you in the AWS Amplify Console that can be accessed by running `amplify console`. The Console provides a list of backend environments, deep links to provisioned resources per Amplify category, status of recent deployments, and instructions on how to promote, clone, pull, and delete backend resources

## Install Amplify libraries

In addition to `aws-amplify` core, install the Angular Ionic modules which provide a service provider, helpers, and components.

```
$ npm install aws-amplify @aws-amplify/ui-angular
```
