name: Fetch Amplify Backend
description: Downloads Amplify configurations after getting temporary AWS credentials
inputs:
  aws-region:
    required: true
  role-to-assume:
    required: true
  app-id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Add Amplify CLI
      run: yarn global add @aws-amplify/cli
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        role-duration-seconds: 900

    - name: Create AWS profile
      run: chmod +x ./build_support/create-test-profile.sh && ./build_support/create-test-profile.sh
      shell: bash

    - name: Pull down AWS environments
      run: chmod +x ./build_support/pull-environment.sh && ./build_support/pull-environment.sh
      shell: bash
      env:
        APP_ID: ${{ inputs.app-id }}

    - name: Delete AWS profile
      run: rm -rf ~/.aws
      shell: bash