// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4b632a29-b6d8-487f-bac4-c4311a5ab725",
    "aws_cognito_region": "us-west-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "53496f1ec97f4f57b6f9b1b5df579cda",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
