/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SelectedFilters, SelectedTabHeadings, SetNewSelectedTabHeadings } from "./docs-ui/page/page.types";
import { FeatureFlag, Value } from "./amplify-ui/cli-feature-flag/feature-flag.types";
import { ToggleInView } from "./amplify-ui/sidebar-layout/sidebar-layout.types";
import { SetContent } from "./amplify-ui/toc/toc.types";
import { MenuGroup, Page } from "./api";
import { CustomComponentName } from "./docs-ui/component-playground/component-playground.types";
import { SwitchOption } from "./docs-ui/version-switch/version-switch.types";
import { WebComponentProps } from "./docs-ui/ui-component-props/ui-component-props.types";
export namespace Components {
    interface AmplifyBlock {
        /**
          * Block name
         */
        "name"?: string;
    }
    interface AmplifyBlockSwitcher {
        /**
          * increments whenever the platform changes and we need to refresh the tabHeadings
         */
        "alwaysRerenderBlockSwitcher": number;
        /**
          * list of previously tab headings in order of priority, passed from global provider
         */
        "selectedTabHeadings": SelectedTabHeadings;
        /**
          * tack on a new tab heading at highest priority
         */
        "setNewSelectedTabHeadings": SetNewSelectedTabHeadings;
    }
    interface AmplifyCallout {
        /**
          * * is it a warning?
         */
        "warning"?: boolean;
    }
    interface AmplifyCodeBlock {
        /**
          * what language are we displaying
         */
        "language": string;
        /**
          * the number of lines of the code block
         */
        "lineCount": number;
    }
    interface AmplifyExternalLink {
        /**
          * * Title attr same as for `a`
         */
        "anchorTitle"?: string;
        /**
          * * Whether to display the external link graphic to the right of the anchor child text
         */
        "graphic"?: "black" | "white";
        /**
          * * The URL to open / to which the anchor should redirect
         */
        "href"?: string;
        /**
          * * Whether to cancel the overriden target behavior (defaults to "_blank")
         */
        "redirect"?: boolean;
    }
    interface AmplifyFeatureFlagSummary {
        /**
          * data of the feature flag
         */
        "feature": FeatureFlag;
        /**
          * name of the feature flag
         */
        "name": string;
    }
    interface AmplifyFeatureFlagValues {
        /**
          * name of the feature flag
         */
        "name": string;
        /**
          * data of the feature flag
         */
        "values": Value[];
    }
    interface AmplifyFeatureFlags {
    }
    interface AmplifyLorem {
    }
    interface AmplifyResponsiveGrid {
        /**
          * default column count for laptop
         */
        "columns": number;
        /**
          * how much space in between grid items (ems)
         */
        "gridGap": number;
    }
    interface AmplifySidebarCloseButton {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
    }
    interface AmplifySidebarLayout {
    }
    interface AmplifySidebarLayoutMain {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
    }
    interface AmplifySidebarLayoutSidebar {
        /**
          * * is the sidebar hidden? This prop is passed via `sidebar-context`
         */
        "inView"?: boolean;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
        /**
          * * at what distance from the viewport top should the bar be affixed?
         */
        "top"?: number;
    }
    interface AmplifySidebarLayoutToggle {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
        /**
          * * when the sidebar is in view, what class should be appended to the button?
         */
        "inViewClass"?: string;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
    }
    interface AmplifySidebarOpenButton {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
    }
    interface AmplifyToc {
        /**
          * A list of `h2` and/or `h3` nodes, provided by either of 2 means: 1. User-provided (`<amplify-toc elements={[...h2h3DomNodes]} />`) 2. Provider-injected (within parent `amplify-toc-provider`, sibling an `amplify-toc-content` instance)
         */
        "elements"?: HTMLElement[];
        /**
          * Whether or not the left sidebar is in view; injected from the sidebar context. If the left sidebar isn't in view, there is more space for this table of contents
         */
        "inView"?: boolean;
        /**
          * * the title of the page on which this TOC is being rendered
         */
        "pageTitle"?: string;
        /**
          * * offset the active item (useful when combatting sticky header)
         */
        "stickyHeaderHeight": 54;
    }
    interface AmplifyTocContents {
        /**
          * Sets `content` prop within parent `amplify-toc-provider`, which propogates into the provider's child `amplify-toc` instances
         */
        "setContent"?: SetContent;
    }
    interface AmplifyTocProvider {
    }
    interface Docs404Page {
    }
    interface DocsCard {
        /**
          * * query string parameters to attach to the link
         */
        "QSPs": string;
        /**
          * * link tag to use
         */
        "containertag": string;
        /**
          * * whether or not to show external link graphic
         */
        "external"?: boolean;
        /**
          * * the global filter state
         */
        "selectedFilters"?: SelectedFilters;
        /**
          * * url
         */
        "url"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForAndroidFilter"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForIOSFilter"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForJSFilter"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForMobileFilter"?: string;
        /**
          * * if true, the thumbnail gets rendered to the left of the detail (not above)
         */
        "vertical"?: boolean;
    }
    interface DocsChooseAnchor {
        /**
          * * the current page's data
         */
        "page": Page;
    }
    interface DocsChooseIntegrationAnchor {
        /**
          * * the current page's data
         */
        "page"?: Page;
    }
    interface DocsComponentPlayground {
        /**
          * Name of component used in the playground
         */
        "componentName": CustomComponentName;
    }
    interface DocsContainer {
        /**
          * * incase users want to add a class to the inner div
         */
        "innerClass"?: string;
    }
    interface DocsFeedbackCallout {
    }
    interface DocsFooter {
    }
    interface DocsFourOFour {
    }
    interface DocsHero {
    }
    interface DocsInPageLink {
        /**
          * * the selected filter state
         */
        "selectedFilters": SelectedFilters;
        /**
          * * the id of the element this link points to
         */
        "targetId": string;
    }
    interface DocsInternalLink {
        /**
          * * query string parameters to attach to the link
         */
        "QSPs": string;
        /**
          * * class name to attach to link when active
         */
        "activeClass"?: string;
        /**
          * * override `isChildActive` to true
         */
        "additionalActiveChildRoots"?: string[];
        /**
          * * class name to attach a subpage is active
         */
        "childActiveClass"?: string;
        /**
          * * the route to render out
         */
        "href": string;
        /**
          * * the global selected filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsInternalLinkButton {
        /**
          * * query string parameters to attach to the link
         */
        "QSPs": string;
        /**
          * * the path to redirect to (internal only!)
         */
        "href"?: string;
    }
    interface DocsLandingHeroCta {
    }
    interface DocsLinkBanner {
    }
    interface DocsMenu {
        /**
          * * the filter key
         */
        "filterKey"?: string;
        /**
          * * the `Page` instance for which this menu is being rendered
         */
        "page"?: Page;
        /**
          * * the currently-selected filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsMenuGroup {
        /**
          * * the filter key that applies to this product section
         */
        "filterKey"?: string;
        /**
          * * whether or not the menu is in view
         */
        "inView"?: boolean;
        /**
          * * the group to render
         */
        "menuGroup"?: MenuGroup;
        /**
          * * the currently-selected filters
         */
        "selectedFilters": SelectedFilters;
        /**
          * * the menu toggle
         */
        "toggleInView": ToggleInView;
    }
    interface DocsNextPrevious {
        /**
          * * page from with `next` and `previous` can be attained
         */
        "page"?: Page;
        /**
          * * currently-selected filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsPage {
    }
    interface DocsRepoActions {
        /**
          * * the page from which a subpath can be attained
         */
        "page"?: Page;
    }
    interface DocsRouter {
    }
    interface DocsSearchBar {
    }
    interface DocsSecondaryNav {
        /**
          * * whether or not the current page has a menu
         */
        "pageHasMenu"?: boolean;
        /**
          * * the current filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsSelectAnchor {
        /**
          * * whether or not the menu is in view
         */
        "inView"?: boolean;
        /**
          * the current page's data
         */
        "page"?: Page;
        /**
          * * the globally-selected filter state
         */
        "selectedFilters"?: SelectedFilters;
        /**
          * * the menu toggle
         */
        "toggleInView": ToggleInView;
    }
    interface DocsUniversalNav {
        /**
          * * image url for brand icon
         */
        "brandIcon"?: string;
        /**
          * * what label should go next to the brand icon?
         */
        "heading"?: string;
    }
    interface DocsUniversalNavBlend {
        /**
          * * image url for brand icon when nav in blend mode
         */
        "brandIcon"?: string;
        /**
          * * what label should go next to the brand icon?
         */
        "heading"?: string;
    }
    interface DocsVersionSwitch {
        /**
          * * Switcher option appearing to the left **
         */
        "leftOption": SwitchOption;
        /**
          * * Switcher option appearing to the right **
         */
        "rightOption": SwitchOption;
    }
    interface UiComponentProps {
        /**
          * Desired property to document
         */
        "propType": WebComponentProps;
        /**
          * * component tag for documented component page
         */
        "tag": string;
        /**
          * * whether or not the table contains header tags
         */
        "useTableHeaders": boolean;
    }
}
declare global {
    interface HTMLAmplifyBlockElement extends Components.AmplifyBlock, HTMLStencilElement {
    }
    var HTMLAmplifyBlockElement: {
        prototype: HTMLAmplifyBlockElement;
        new (): HTMLAmplifyBlockElement;
    };
    interface HTMLAmplifyBlockSwitcherElement extends Components.AmplifyBlockSwitcher, HTMLStencilElement {
    }
    var HTMLAmplifyBlockSwitcherElement: {
        prototype: HTMLAmplifyBlockSwitcherElement;
        new (): HTMLAmplifyBlockSwitcherElement;
    };
    interface HTMLAmplifyCalloutElement extends Components.AmplifyCallout, HTMLStencilElement {
    }
    var HTMLAmplifyCalloutElement: {
        prototype: HTMLAmplifyCalloutElement;
        new (): HTMLAmplifyCalloutElement;
    };
    interface HTMLAmplifyCodeBlockElement extends Components.AmplifyCodeBlock, HTMLStencilElement {
    }
    var HTMLAmplifyCodeBlockElement: {
        prototype: HTMLAmplifyCodeBlockElement;
        new (): HTMLAmplifyCodeBlockElement;
    };
    interface HTMLAmplifyExternalLinkElement extends Components.AmplifyExternalLink, HTMLStencilElement {
    }
    var HTMLAmplifyExternalLinkElement: {
        prototype: HTMLAmplifyExternalLinkElement;
        new (): HTMLAmplifyExternalLinkElement;
    };
    interface HTMLAmplifyFeatureFlagSummaryElement extends Components.AmplifyFeatureFlagSummary, HTMLStencilElement {
    }
    var HTMLAmplifyFeatureFlagSummaryElement: {
        prototype: HTMLAmplifyFeatureFlagSummaryElement;
        new (): HTMLAmplifyFeatureFlagSummaryElement;
    };
    interface HTMLAmplifyFeatureFlagValuesElement extends Components.AmplifyFeatureFlagValues, HTMLStencilElement {
    }
    var HTMLAmplifyFeatureFlagValuesElement: {
        prototype: HTMLAmplifyFeatureFlagValuesElement;
        new (): HTMLAmplifyFeatureFlagValuesElement;
    };
    interface HTMLAmplifyFeatureFlagsElement extends Components.AmplifyFeatureFlags, HTMLStencilElement {
    }
    var HTMLAmplifyFeatureFlagsElement: {
        prototype: HTMLAmplifyFeatureFlagsElement;
        new (): HTMLAmplifyFeatureFlagsElement;
    };
    interface HTMLAmplifyLoremElement extends Components.AmplifyLorem, HTMLStencilElement {
    }
    var HTMLAmplifyLoremElement: {
        prototype: HTMLAmplifyLoremElement;
        new (): HTMLAmplifyLoremElement;
    };
    interface HTMLAmplifyResponsiveGridElement extends Components.AmplifyResponsiveGrid, HTMLStencilElement {
    }
    var HTMLAmplifyResponsiveGridElement: {
        prototype: HTMLAmplifyResponsiveGridElement;
        new (): HTMLAmplifyResponsiveGridElement;
    };
    interface HTMLAmplifySidebarCloseButtonElement extends Components.AmplifySidebarCloseButton, HTMLStencilElement {
    }
    var HTMLAmplifySidebarCloseButtonElement: {
        prototype: HTMLAmplifySidebarCloseButtonElement;
        new (): HTMLAmplifySidebarCloseButtonElement;
    };
    interface HTMLAmplifySidebarLayoutElement extends Components.AmplifySidebarLayout, HTMLStencilElement {
    }
    var HTMLAmplifySidebarLayoutElement: {
        prototype: HTMLAmplifySidebarLayoutElement;
        new (): HTMLAmplifySidebarLayoutElement;
    };
    interface HTMLAmplifySidebarLayoutMainElement extends Components.AmplifySidebarLayoutMain, HTMLStencilElement {
    }
    var HTMLAmplifySidebarLayoutMainElement: {
        prototype: HTMLAmplifySidebarLayoutMainElement;
        new (): HTMLAmplifySidebarLayoutMainElement;
    };
    interface HTMLAmplifySidebarLayoutSidebarElement extends Components.AmplifySidebarLayoutSidebar, HTMLStencilElement {
    }
    var HTMLAmplifySidebarLayoutSidebarElement: {
        prototype: HTMLAmplifySidebarLayoutSidebarElement;
        new (): HTMLAmplifySidebarLayoutSidebarElement;
    };
    interface HTMLAmplifySidebarLayoutToggleElement extends Components.AmplifySidebarLayoutToggle, HTMLStencilElement {
    }
    var HTMLAmplifySidebarLayoutToggleElement: {
        prototype: HTMLAmplifySidebarLayoutToggleElement;
        new (): HTMLAmplifySidebarLayoutToggleElement;
    };
    interface HTMLAmplifySidebarOpenButtonElement extends Components.AmplifySidebarOpenButton, HTMLStencilElement {
    }
    var HTMLAmplifySidebarOpenButtonElement: {
        prototype: HTMLAmplifySidebarOpenButtonElement;
        new (): HTMLAmplifySidebarOpenButtonElement;
    };
    interface HTMLAmplifyTocElement extends Components.AmplifyToc, HTMLStencilElement {
    }
    var HTMLAmplifyTocElement: {
        prototype: HTMLAmplifyTocElement;
        new (): HTMLAmplifyTocElement;
    };
    interface HTMLAmplifyTocContentsElement extends Components.AmplifyTocContents, HTMLStencilElement {
    }
    var HTMLAmplifyTocContentsElement: {
        prototype: HTMLAmplifyTocContentsElement;
        new (): HTMLAmplifyTocContentsElement;
    };
    interface HTMLAmplifyTocProviderElement extends Components.AmplifyTocProvider, HTMLStencilElement {
    }
    var HTMLAmplifyTocProviderElement: {
        prototype: HTMLAmplifyTocProviderElement;
        new (): HTMLAmplifyTocProviderElement;
    };
    interface HTMLDocs404PageElement extends Components.Docs404Page, HTMLStencilElement {
    }
    var HTMLDocs404PageElement: {
        prototype: HTMLDocs404PageElement;
        new (): HTMLDocs404PageElement;
    };
    interface HTMLDocsCardElement extends Components.DocsCard, HTMLStencilElement {
    }
    var HTMLDocsCardElement: {
        prototype: HTMLDocsCardElement;
        new (): HTMLDocsCardElement;
    };
    interface HTMLDocsChooseAnchorElement extends Components.DocsChooseAnchor, HTMLStencilElement {
    }
    var HTMLDocsChooseAnchorElement: {
        prototype: HTMLDocsChooseAnchorElement;
        new (): HTMLDocsChooseAnchorElement;
    };
    interface HTMLDocsChooseIntegrationAnchorElement extends Components.DocsChooseIntegrationAnchor, HTMLStencilElement {
    }
    var HTMLDocsChooseIntegrationAnchorElement: {
        prototype: HTMLDocsChooseIntegrationAnchorElement;
        new (): HTMLDocsChooseIntegrationAnchorElement;
    };
    interface HTMLDocsComponentPlaygroundElement extends Components.DocsComponentPlayground, HTMLStencilElement {
    }
    var HTMLDocsComponentPlaygroundElement: {
        prototype: HTMLDocsComponentPlaygroundElement;
        new (): HTMLDocsComponentPlaygroundElement;
    };
    interface HTMLDocsContainerElement extends Components.DocsContainer, HTMLStencilElement {
    }
    var HTMLDocsContainerElement: {
        prototype: HTMLDocsContainerElement;
        new (): HTMLDocsContainerElement;
    };
    interface HTMLDocsFeedbackCalloutElement extends Components.DocsFeedbackCallout, HTMLStencilElement {
    }
    var HTMLDocsFeedbackCalloutElement: {
        prototype: HTMLDocsFeedbackCalloutElement;
        new (): HTMLDocsFeedbackCalloutElement;
    };
    interface HTMLDocsFooterElement extends Components.DocsFooter, HTMLStencilElement {
    }
    var HTMLDocsFooterElement: {
        prototype: HTMLDocsFooterElement;
        new (): HTMLDocsFooterElement;
    };
    interface HTMLDocsFourOFourElement extends Components.DocsFourOFour, HTMLStencilElement {
    }
    var HTMLDocsFourOFourElement: {
        prototype: HTMLDocsFourOFourElement;
        new (): HTMLDocsFourOFourElement;
    };
    interface HTMLDocsHeroElement extends Components.DocsHero, HTMLStencilElement {
    }
    var HTMLDocsHeroElement: {
        prototype: HTMLDocsHeroElement;
        new (): HTMLDocsHeroElement;
    };
    interface HTMLDocsInPageLinkElement extends Components.DocsInPageLink, HTMLStencilElement {
    }
    var HTMLDocsInPageLinkElement: {
        prototype: HTMLDocsInPageLinkElement;
        new (): HTMLDocsInPageLinkElement;
    };
    interface HTMLDocsInternalLinkElement extends Components.DocsInternalLink, HTMLStencilElement {
    }
    var HTMLDocsInternalLinkElement: {
        prototype: HTMLDocsInternalLinkElement;
        new (): HTMLDocsInternalLinkElement;
    };
    interface HTMLDocsInternalLinkButtonElement extends Components.DocsInternalLinkButton, HTMLStencilElement {
    }
    var HTMLDocsInternalLinkButtonElement: {
        prototype: HTMLDocsInternalLinkButtonElement;
        new (): HTMLDocsInternalLinkButtonElement;
    };
    interface HTMLDocsLandingHeroCtaElement extends Components.DocsLandingHeroCta, HTMLStencilElement {
    }
    var HTMLDocsLandingHeroCtaElement: {
        prototype: HTMLDocsLandingHeroCtaElement;
        new (): HTMLDocsLandingHeroCtaElement;
    };
    interface HTMLDocsLinkBannerElement extends Components.DocsLinkBanner, HTMLStencilElement {
    }
    var HTMLDocsLinkBannerElement: {
        prototype: HTMLDocsLinkBannerElement;
        new (): HTMLDocsLinkBannerElement;
    };
    interface HTMLDocsMenuElement extends Components.DocsMenu, HTMLStencilElement {
    }
    var HTMLDocsMenuElement: {
        prototype: HTMLDocsMenuElement;
        new (): HTMLDocsMenuElement;
    };
    interface HTMLDocsMenuGroupElement extends Components.DocsMenuGroup, HTMLStencilElement {
    }
    var HTMLDocsMenuGroupElement: {
        prototype: HTMLDocsMenuGroupElement;
        new (): HTMLDocsMenuGroupElement;
    };
    interface HTMLDocsNextPreviousElement extends Components.DocsNextPrevious, HTMLStencilElement {
    }
    var HTMLDocsNextPreviousElement: {
        prototype: HTMLDocsNextPreviousElement;
        new (): HTMLDocsNextPreviousElement;
    };
    interface HTMLDocsPageElement extends Components.DocsPage, HTMLStencilElement {
    }
    var HTMLDocsPageElement: {
        prototype: HTMLDocsPageElement;
        new (): HTMLDocsPageElement;
    };
    interface HTMLDocsRepoActionsElement extends Components.DocsRepoActions, HTMLStencilElement {
    }
    var HTMLDocsRepoActionsElement: {
        prototype: HTMLDocsRepoActionsElement;
        new (): HTMLDocsRepoActionsElement;
    };
    interface HTMLDocsRouterElement extends Components.DocsRouter, HTMLStencilElement {
    }
    var HTMLDocsRouterElement: {
        prototype: HTMLDocsRouterElement;
        new (): HTMLDocsRouterElement;
    };
    interface HTMLDocsSearchBarElement extends Components.DocsSearchBar, HTMLStencilElement {
    }
    var HTMLDocsSearchBarElement: {
        prototype: HTMLDocsSearchBarElement;
        new (): HTMLDocsSearchBarElement;
    };
    interface HTMLDocsSecondaryNavElement extends Components.DocsSecondaryNav, HTMLStencilElement {
    }
    var HTMLDocsSecondaryNavElement: {
        prototype: HTMLDocsSecondaryNavElement;
        new (): HTMLDocsSecondaryNavElement;
    };
    interface HTMLDocsSelectAnchorElement extends Components.DocsSelectAnchor, HTMLStencilElement {
    }
    var HTMLDocsSelectAnchorElement: {
        prototype: HTMLDocsSelectAnchorElement;
        new (): HTMLDocsSelectAnchorElement;
    };
    interface HTMLDocsUniversalNavElement extends Components.DocsUniversalNav, HTMLStencilElement {
    }
    var HTMLDocsUniversalNavElement: {
        prototype: HTMLDocsUniversalNavElement;
        new (): HTMLDocsUniversalNavElement;
    };
    interface HTMLDocsUniversalNavBlendElement extends Components.DocsUniversalNavBlend, HTMLStencilElement {
    }
    var HTMLDocsUniversalNavBlendElement: {
        prototype: HTMLDocsUniversalNavBlendElement;
        new (): HTMLDocsUniversalNavBlendElement;
    };
    interface HTMLDocsVersionSwitchElement extends Components.DocsVersionSwitch, HTMLStencilElement {
    }
    var HTMLDocsVersionSwitchElement: {
        prototype: HTMLDocsVersionSwitchElement;
        new (): HTMLDocsVersionSwitchElement;
    };
    interface HTMLUiComponentPropsElement extends Components.UiComponentProps, HTMLStencilElement {
    }
    var HTMLUiComponentPropsElement: {
        prototype: HTMLUiComponentPropsElement;
        new (): HTMLUiComponentPropsElement;
    };
    interface HTMLElementTagNameMap {
        "amplify-block": HTMLAmplifyBlockElement;
        "amplify-block-switcher": HTMLAmplifyBlockSwitcherElement;
        "amplify-callout": HTMLAmplifyCalloutElement;
        "amplify-code-block": HTMLAmplifyCodeBlockElement;
        "amplify-external-link": HTMLAmplifyExternalLinkElement;
        "amplify-feature-flag-summary": HTMLAmplifyFeatureFlagSummaryElement;
        "amplify-feature-flag-values": HTMLAmplifyFeatureFlagValuesElement;
        "amplify-feature-flags": HTMLAmplifyFeatureFlagsElement;
        "amplify-lorem": HTMLAmplifyLoremElement;
        "amplify-responsive-grid": HTMLAmplifyResponsiveGridElement;
        "amplify-sidebar-close-button": HTMLAmplifySidebarCloseButtonElement;
        "amplify-sidebar-layout": HTMLAmplifySidebarLayoutElement;
        "amplify-sidebar-layout-main": HTMLAmplifySidebarLayoutMainElement;
        "amplify-sidebar-layout-sidebar": HTMLAmplifySidebarLayoutSidebarElement;
        "amplify-sidebar-layout-toggle": HTMLAmplifySidebarLayoutToggleElement;
        "amplify-sidebar-open-button": HTMLAmplifySidebarOpenButtonElement;
        "amplify-toc": HTMLAmplifyTocElement;
        "amplify-toc-contents": HTMLAmplifyTocContentsElement;
        "amplify-toc-provider": HTMLAmplifyTocProviderElement;
        "docs-404-page": HTMLDocs404PageElement;
        "docs-card": HTMLDocsCardElement;
        "docs-choose-anchor": HTMLDocsChooseAnchorElement;
        "docs-choose-integration-anchor": HTMLDocsChooseIntegrationAnchorElement;
        "docs-component-playground": HTMLDocsComponentPlaygroundElement;
        "docs-container": HTMLDocsContainerElement;
        "docs-feedback-callout": HTMLDocsFeedbackCalloutElement;
        "docs-footer": HTMLDocsFooterElement;
        "docs-four-o-four": HTMLDocsFourOFourElement;
        "docs-hero": HTMLDocsHeroElement;
        "docs-in-page-link": HTMLDocsInPageLinkElement;
        "docs-internal-link": HTMLDocsInternalLinkElement;
        "docs-internal-link-button": HTMLDocsInternalLinkButtonElement;
        "docs-landing-hero-cta": HTMLDocsLandingHeroCtaElement;
        "docs-link-banner": HTMLDocsLinkBannerElement;
        "docs-menu": HTMLDocsMenuElement;
        "docs-menu-group": HTMLDocsMenuGroupElement;
        "docs-next-previous": HTMLDocsNextPreviousElement;
        "docs-page": HTMLDocsPageElement;
        "docs-repo-actions": HTMLDocsRepoActionsElement;
        "docs-router": HTMLDocsRouterElement;
        "docs-search-bar": HTMLDocsSearchBarElement;
        "docs-secondary-nav": HTMLDocsSecondaryNavElement;
        "docs-select-anchor": HTMLDocsSelectAnchorElement;
        "docs-universal-nav": HTMLDocsUniversalNavElement;
        "docs-universal-nav-blend": HTMLDocsUniversalNavBlendElement;
        "docs-version-switch": HTMLDocsVersionSwitchElement;
        "ui-component-props": HTMLUiComponentPropsElement;
    }
}
declare namespace LocalJSX {
    interface AmplifyBlock {
        /**
          * Block name
         */
        "name"?: string;
    }
    interface AmplifyBlockSwitcher {
        /**
          * increments whenever the platform changes and we need to refresh the tabHeadings
         */
        "alwaysRerenderBlockSwitcher"?: number;
        /**
          * list of previously tab headings in order of priority, passed from global provider
         */
        "selectedTabHeadings"?: SelectedTabHeadings;
        /**
          * tack on a new tab heading at highest priority
         */
        "setNewSelectedTabHeadings"?: SetNewSelectedTabHeadings;
    }
    interface AmplifyCallout {
        /**
          * * is it a warning?
         */
        "warning"?: boolean;
    }
    interface AmplifyCodeBlock {
        /**
          * what language are we displaying
         */
        "language"?: string;
        /**
          * the number of lines of the code block
         */
        "lineCount"?: number;
    }
    interface AmplifyExternalLink {
        /**
          * * Title attr same as for `a`
         */
        "anchorTitle"?: string;
        /**
          * * Whether to display the external link graphic to the right of the anchor child text
         */
        "graphic"?: "black" | "white";
        /**
          * * The URL to open / to which the anchor should redirect
         */
        "href"?: string;
        /**
          * * Whether to cancel the overriden target behavior (defaults to "_blank")
         */
        "redirect"?: boolean;
    }
    interface AmplifyFeatureFlagSummary {
        /**
          * data of the feature flag
         */
        "feature"?: FeatureFlag;
        /**
          * name of the feature flag
         */
        "name"?: string;
    }
    interface AmplifyFeatureFlagValues {
        /**
          * name of the feature flag
         */
        "name"?: string;
        /**
          * data of the feature flag
         */
        "values"?: Value[];
    }
    interface AmplifyFeatureFlags {
    }
    interface AmplifyLorem {
    }
    interface AmplifyResponsiveGrid {
        /**
          * default column count for laptop
         */
        "columns"?: number;
        /**
          * how much space in between grid items (ems)
         */
        "gridGap"?: number;
    }
    interface AmplifySidebarCloseButton {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
    }
    interface AmplifySidebarLayout {
    }
    interface AmplifySidebarLayoutMain {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
    }
    interface AmplifySidebarLayoutSidebar {
        /**
          * * is the sidebar hidden? This prop is passed via `sidebar-context`
         */
        "inView"?: boolean;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
        /**
          * * at what distance from the viewport top should the bar be affixed?
         */
        "top"?: number;
    }
    interface AmplifySidebarLayoutToggle {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
        /**
          * * when the sidebar is in view, what class should be appended to the button?
         */
        "inViewClass"?: string;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
    }
    interface AmplifySidebarOpenButton {
        /**
          * * whether or not the sidebar is in view, provided by `sidebar-layout`
         */
        "inView"?: boolean;
        /**
          * * toggles the state provided by `sidebar-layout`
         */
        "toggleInView"?: ToggleInView;
    }
    interface AmplifyToc {
        /**
          * A list of `h2` and/or `h3` nodes, provided by either of 2 means: 1. User-provided (`<amplify-toc elements={[...h2h3DomNodes]} />`) 2. Provider-injected (within parent `amplify-toc-provider`, sibling an `amplify-toc-content` instance)
         */
        "elements"?: HTMLElement[];
        /**
          * Whether or not the left sidebar is in view; injected from the sidebar context. If the left sidebar isn't in view, there is more space for this table of contents
         */
        "inView"?: boolean;
        /**
          * * the title of the page on which this TOC is being rendered
         */
        "pageTitle"?: string;
        /**
          * * offset the active item (useful when combatting sticky header)
         */
        "stickyHeaderHeight"?: 54;
    }
    interface AmplifyTocContents {
        /**
          * Sets `content` prop within parent `amplify-toc-provider`, which propogates into the provider's child `amplify-toc` instances
         */
        "setContent"?: SetContent;
    }
    interface AmplifyTocProvider {
    }
    interface Docs404Page {
    }
    interface DocsCard {
        /**
          * * query string parameters to attach to the link
         */
        "QSPs"?: string;
        /**
          * * link tag to use
         */
        "containertag"?: string;
        /**
          * * whether or not to show external link graphic
         */
        "external"?: boolean;
        /**
          * * the global filter state
         */
        "selectedFilters"?: SelectedFilters;
        /**
          * * url
         */
        "url"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForAndroidFilter"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForIOSFilter"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForJSFilter"?: string;
        /**
          * * add a different url when mobile selected
         */
        "urlOverrideForMobileFilter"?: string;
        /**
          * * if true, the thumbnail gets rendered to the left of the detail (not above)
         */
        "vertical"?: boolean;
    }
    interface DocsChooseAnchor {
        /**
          * * the current page's data
         */
        "page"?: Page;
    }
    interface DocsChooseIntegrationAnchor {
        /**
          * * the current page's data
         */
        "page"?: Page;
    }
    interface DocsComponentPlayground {
        /**
          * Name of component used in the playground
         */
        "componentName"?: CustomComponentName;
    }
    interface DocsContainer {
        /**
          * * incase users want to add a class to the inner div
         */
        "innerClass"?: string;
    }
    interface DocsFeedbackCallout {
    }
    interface DocsFooter {
    }
    interface DocsFourOFour {
    }
    interface DocsHero {
    }
    interface DocsInPageLink {
        /**
          * * the selected filter state
         */
        "selectedFilters"?: SelectedFilters;
        /**
          * * the id of the element this link points to
         */
        "targetId"?: string;
    }
    interface DocsInternalLink {
        /**
          * * query string parameters to attach to the link
         */
        "QSPs"?: string;
        /**
          * * class name to attach to link when active
         */
        "activeClass"?: string;
        /**
          * * override `isChildActive` to true
         */
        "additionalActiveChildRoots"?: string[];
        /**
          * * class name to attach a subpage is active
         */
        "childActiveClass"?: string;
        /**
          * * the route to render out
         */
        "href"?: string;
        /**
          * * the global selected filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsInternalLinkButton {
        /**
          * * query string parameters to attach to the link
         */
        "QSPs"?: string;
        /**
          * * the path to redirect to (internal only!)
         */
        "href"?: string;
    }
    interface DocsLandingHeroCta {
    }
    interface DocsLinkBanner {
    }
    interface DocsMenu {
        /**
          * * the filter key
         */
        "filterKey"?: string;
        /**
          * * the `Page` instance for which this menu is being rendered
         */
        "page"?: Page;
        /**
          * * the currently-selected filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsMenuGroup {
        /**
          * * the filter key that applies to this product section
         */
        "filterKey"?: string;
        /**
          * * whether or not the menu is in view
         */
        "inView"?: boolean;
        /**
          * * the group to render
         */
        "menuGroup"?: MenuGroup;
        /**
          * * the currently-selected filters
         */
        "selectedFilters"?: SelectedFilters;
        /**
          * * the menu toggle
         */
        "toggleInView"?: ToggleInView;
    }
    interface DocsNextPrevious {
        /**
          * * page from with `next` and `previous` can be attained
         */
        "page"?: Page;
        /**
          * * currently-selected filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsPage {
    }
    interface DocsRepoActions {
        /**
          * * the page from which a subpath can be attained
         */
        "page"?: Page;
    }
    interface DocsRouter {
    }
    interface DocsSearchBar {
    }
    interface DocsSecondaryNav {
        /**
          * * whether or not the current page has a menu
         */
        "pageHasMenu"?: boolean;
        /**
          * * the current filter state
         */
        "selectedFilters"?: SelectedFilters;
    }
    interface DocsSelectAnchor {
        /**
          * * whether or not the menu is in view
         */
        "inView"?: boolean;
        /**
          * the current page's data
         */
        "page"?: Page;
        /**
          * * the globally-selected filter state
         */
        "selectedFilters"?: SelectedFilters;
        /**
          * * the menu toggle
         */
        "toggleInView"?: ToggleInView;
    }
    interface DocsUniversalNav {
        /**
          * * image url for brand icon
         */
        "brandIcon"?: string;
        /**
          * * what label should go next to the brand icon?
         */
        "heading"?: string;
    }
    interface DocsUniversalNavBlend {
        /**
          * * image url for brand icon when nav in blend mode
         */
        "brandIcon"?: string;
        /**
          * * what label should go next to the brand icon?
         */
        "heading"?: string;
    }
    interface DocsVersionSwitch {
        /**
          * * Switcher option appearing to the left **
         */
        "leftOption"?: SwitchOption;
        /**
          * * Switcher option appearing to the right **
         */
        "rightOption"?: SwitchOption;
    }
    interface UiComponentProps {
        /**
          * Desired property to document
         */
        "propType"?: WebComponentProps;
        /**
          * * component tag for documented component page
         */
        "tag"?: string;
        /**
          * * whether or not the table contains header tags
         */
        "useTableHeaders"?: boolean;
    }
    interface IntrinsicElements {
        "amplify-block": AmplifyBlock;
        "amplify-block-switcher": AmplifyBlockSwitcher;
        "amplify-callout": AmplifyCallout;
        "amplify-code-block": AmplifyCodeBlock;
        "amplify-external-link": AmplifyExternalLink;
        "amplify-feature-flag-summary": AmplifyFeatureFlagSummary;
        "amplify-feature-flag-values": AmplifyFeatureFlagValues;
        "amplify-feature-flags": AmplifyFeatureFlags;
        "amplify-lorem": AmplifyLorem;
        "amplify-responsive-grid": AmplifyResponsiveGrid;
        "amplify-sidebar-close-button": AmplifySidebarCloseButton;
        "amplify-sidebar-layout": AmplifySidebarLayout;
        "amplify-sidebar-layout-main": AmplifySidebarLayoutMain;
        "amplify-sidebar-layout-sidebar": AmplifySidebarLayoutSidebar;
        "amplify-sidebar-layout-toggle": AmplifySidebarLayoutToggle;
        "amplify-sidebar-open-button": AmplifySidebarOpenButton;
        "amplify-toc": AmplifyToc;
        "amplify-toc-contents": AmplifyTocContents;
        "amplify-toc-provider": AmplifyTocProvider;
        "docs-404-page": Docs404Page;
        "docs-card": DocsCard;
        "docs-choose-anchor": DocsChooseAnchor;
        "docs-choose-integration-anchor": DocsChooseIntegrationAnchor;
        "docs-component-playground": DocsComponentPlayground;
        "docs-container": DocsContainer;
        "docs-feedback-callout": DocsFeedbackCallout;
        "docs-footer": DocsFooter;
        "docs-four-o-four": DocsFourOFour;
        "docs-hero": DocsHero;
        "docs-in-page-link": DocsInPageLink;
        "docs-internal-link": DocsInternalLink;
        "docs-internal-link-button": DocsInternalLinkButton;
        "docs-landing-hero-cta": DocsLandingHeroCta;
        "docs-link-banner": DocsLinkBanner;
        "docs-menu": DocsMenu;
        "docs-menu-group": DocsMenuGroup;
        "docs-next-previous": DocsNextPrevious;
        "docs-page": DocsPage;
        "docs-repo-actions": DocsRepoActions;
        "docs-router": DocsRouter;
        "docs-search-bar": DocsSearchBar;
        "docs-secondary-nav": DocsSecondaryNav;
        "docs-select-anchor": DocsSelectAnchor;
        "docs-universal-nav": DocsUniversalNav;
        "docs-universal-nav-blend": DocsUniversalNavBlend;
        "docs-version-switch": DocsVersionSwitch;
        "ui-component-props": UiComponentProps;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "amplify-block": LocalJSX.AmplifyBlock & JSXBase.HTMLAttributes<HTMLAmplifyBlockElement>;
            "amplify-block-switcher": LocalJSX.AmplifyBlockSwitcher & JSXBase.HTMLAttributes<HTMLAmplifyBlockSwitcherElement>;
            "amplify-callout": LocalJSX.AmplifyCallout & JSXBase.HTMLAttributes<HTMLAmplifyCalloutElement>;
            "amplify-code-block": LocalJSX.AmplifyCodeBlock & JSXBase.HTMLAttributes<HTMLAmplifyCodeBlockElement>;
            "amplify-external-link": LocalJSX.AmplifyExternalLink & JSXBase.HTMLAttributes<HTMLAmplifyExternalLinkElement>;
            "amplify-feature-flag-summary": LocalJSX.AmplifyFeatureFlagSummary & JSXBase.HTMLAttributes<HTMLAmplifyFeatureFlagSummaryElement>;
            "amplify-feature-flag-values": LocalJSX.AmplifyFeatureFlagValues & JSXBase.HTMLAttributes<HTMLAmplifyFeatureFlagValuesElement>;
            "amplify-feature-flags": LocalJSX.AmplifyFeatureFlags & JSXBase.HTMLAttributes<HTMLAmplifyFeatureFlagsElement>;
            "amplify-lorem": LocalJSX.AmplifyLorem & JSXBase.HTMLAttributes<HTMLAmplifyLoremElement>;
            "amplify-responsive-grid": LocalJSX.AmplifyResponsiveGrid & JSXBase.HTMLAttributes<HTMLAmplifyResponsiveGridElement>;
            "amplify-sidebar-close-button": LocalJSX.AmplifySidebarCloseButton & JSXBase.HTMLAttributes<HTMLAmplifySidebarCloseButtonElement>;
            "amplify-sidebar-layout": LocalJSX.AmplifySidebarLayout & JSXBase.HTMLAttributes<HTMLAmplifySidebarLayoutElement>;
            "amplify-sidebar-layout-main": LocalJSX.AmplifySidebarLayoutMain & JSXBase.HTMLAttributes<HTMLAmplifySidebarLayoutMainElement>;
            "amplify-sidebar-layout-sidebar": LocalJSX.AmplifySidebarLayoutSidebar & JSXBase.HTMLAttributes<HTMLAmplifySidebarLayoutSidebarElement>;
            "amplify-sidebar-layout-toggle": LocalJSX.AmplifySidebarLayoutToggle & JSXBase.HTMLAttributes<HTMLAmplifySidebarLayoutToggleElement>;
            "amplify-sidebar-open-button": LocalJSX.AmplifySidebarOpenButton & JSXBase.HTMLAttributes<HTMLAmplifySidebarOpenButtonElement>;
            "amplify-toc": LocalJSX.AmplifyToc & JSXBase.HTMLAttributes<HTMLAmplifyTocElement>;
            "amplify-toc-contents": LocalJSX.AmplifyTocContents & JSXBase.HTMLAttributes<HTMLAmplifyTocContentsElement>;
            "amplify-toc-provider": LocalJSX.AmplifyTocProvider & JSXBase.HTMLAttributes<HTMLAmplifyTocProviderElement>;
            "docs-404-page": LocalJSX.Docs404Page & JSXBase.HTMLAttributes<HTMLDocs404PageElement>;
            "docs-card": LocalJSX.DocsCard & JSXBase.HTMLAttributes<HTMLDocsCardElement>;
            "docs-choose-anchor": LocalJSX.DocsChooseAnchor & JSXBase.HTMLAttributes<HTMLDocsChooseAnchorElement>;
            "docs-choose-integration-anchor": LocalJSX.DocsChooseIntegrationAnchor & JSXBase.HTMLAttributes<HTMLDocsChooseIntegrationAnchorElement>;
            "docs-component-playground": LocalJSX.DocsComponentPlayground & JSXBase.HTMLAttributes<HTMLDocsComponentPlaygroundElement>;
            "docs-container": LocalJSX.DocsContainer & JSXBase.HTMLAttributes<HTMLDocsContainerElement>;
            "docs-feedback-callout": LocalJSX.DocsFeedbackCallout & JSXBase.HTMLAttributes<HTMLDocsFeedbackCalloutElement>;
            "docs-footer": LocalJSX.DocsFooter & JSXBase.HTMLAttributes<HTMLDocsFooterElement>;
            "docs-four-o-four": LocalJSX.DocsFourOFour & JSXBase.HTMLAttributes<HTMLDocsFourOFourElement>;
            "docs-hero": LocalJSX.DocsHero & JSXBase.HTMLAttributes<HTMLDocsHeroElement>;
            "docs-in-page-link": LocalJSX.DocsInPageLink & JSXBase.HTMLAttributes<HTMLDocsInPageLinkElement>;
            "docs-internal-link": LocalJSX.DocsInternalLink & JSXBase.HTMLAttributes<HTMLDocsInternalLinkElement>;
            "docs-internal-link-button": LocalJSX.DocsInternalLinkButton & JSXBase.HTMLAttributes<HTMLDocsInternalLinkButtonElement>;
            "docs-landing-hero-cta": LocalJSX.DocsLandingHeroCta & JSXBase.HTMLAttributes<HTMLDocsLandingHeroCtaElement>;
            "docs-link-banner": LocalJSX.DocsLinkBanner & JSXBase.HTMLAttributes<HTMLDocsLinkBannerElement>;
            "docs-menu": LocalJSX.DocsMenu & JSXBase.HTMLAttributes<HTMLDocsMenuElement>;
            "docs-menu-group": LocalJSX.DocsMenuGroup & JSXBase.HTMLAttributes<HTMLDocsMenuGroupElement>;
            "docs-next-previous": LocalJSX.DocsNextPrevious & JSXBase.HTMLAttributes<HTMLDocsNextPreviousElement>;
            "docs-page": LocalJSX.DocsPage & JSXBase.HTMLAttributes<HTMLDocsPageElement>;
            "docs-repo-actions": LocalJSX.DocsRepoActions & JSXBase.HTMLAttributes<HTMLDocsRepoActionsElement>;
            "docs-router": LocalJSX.DocsRouter & JSXBase.HTMLAttributes<HTMLDocsRouterElement>;
            "docs-search-bar": LocalJSX.DocsSearchBar & JSXBase.HTMLAttributes<HTMLDocsSearchBarElement>;
            "docs-secondary-nav": LocalJSX.DocsSecondaryNav & JSXBase.HTMLAttributes<HTMLDocsSecondaryNavElement>;
            "docs-select-anchor": LocalJSX.DocsSelectAnchor & JSXBase.HTMLAttributes<HTMLDocsSelectAnchorElement>;
            "docs-universal-nav": LocalJSX.DocsUniversalNav & JSXBase.HTMLAttributes<HTMLDocsUniversalNavElement>;
            "docs-universal-nav-blend": LocalJSX.DocsUniversalNavBlend & JSXBase.HTMLAttributes<HTMLDocsUniversalNavBlendElement>;
            "docs-version-switch": LocalJSX.DocsVersionSwitch & JSXBase.HTMLAttributes<HTMLDocsVersionSwitchElement>;
            "ui-component-props": LocalJSX.UiComponentProps & JSXBase.HTMLAttributes<HTMLUiComponentPropsElement>;
        }
    }
}
