export const redirects = {
  "#model": "/model",
  "#definition": "/model#definition",
  "#usage": "/model#usage",
  "#generates": "/model#generates",
  "#key": "/key",
  "#definition-1": "/key#definition",
  "#how-to-use-key": "/key#how-to-use-key",
  "#designing-data-models-using-key": "/key#designing-data-models-using-key",
  "#evolving-apis-with-key": "/key#evolving-apis-with-key",
  "#combining-key-with-connection": "/key#combining-key-with-connection",
  "#auth": "/auth",
  "#definition-2": "/auth#definition",
  "#owner-authorization": "/auth#owner-authorization",
  "#multiple-authorization-rules": "/auth#multiple-authorization-rules",
  "#ownership-with-create-mutations": "/auth#ownership-with-create-mutations",
  "#static-group-authorization": "/auth#static-group-authorization",
  "#dynamic-group-authorization": "/auth#dynamic-group-authorization",
  "#public-authorization": "/auth#public-authorization",
  "#private-authorization": "/auth#private-authorization",
  "#authorization-using-an-oidc-provider":
    "/auth#authorization-using-an-oidc-provider",
  "#combining-multiple-authorization-types":
    "/auth#combining-multiple-authorization-types",
  "#allowed-authorization-mode-vs-provider-combinations":
    "/auth#allowed-authorization-mode-vs-provider-combinations",
  "#custom-claims": "/auth#custom-claims",
  "#authorizing-subscriptions": "/auth#authorizing-subscriptions",
  "#field-level-authorization": "/auth#field-level-authorization",
  "#static-group-authorization-1": "/auth#static-group-authorization-1",
  "#dynamic-group-authorization-1": "/auth#dynamic-group-authorization-1",
  "#function": "/function",
  "#definition-3": "/function#definition",
  "#usage-1": "/function#usage",
  "#structure-of-the-function-event":
    "/function#structure-of-the-function-event",
  "#calling-functions-in-different-regions":
    "/function#calling-functions-in-different-regions",
  "#chaining-functions": "/function#chaining-functions",
  "#connection": "/connection",
  "#definition-4": "/connection#definition",
  "#usage-2": "/connection#usage",
  "#has-one": "/connection#has-one",
  "#has-many": "/connection#has-many",
  "#belongs-to": "/connection#belongs-to",
  "#many-to-many-connections": "/connection#many-to-many-connections",
  "#limit": "/connection#limit",
  "#generates-3": "/connection#generates",
  "#versioned": "/versioned",
  "#definition-5": "/versioned#definition",
  "#usage-3": "/versioned#usage",
  "#generates-4": "/versioned#generates",
  "#searchable": "/searchable",
  "#definition-6": "/searchable#definition",
  "#usage-4": "/searchable#usage",
  "#known-limitations": "/searchable#known-limitations",
  "#backfill-your-elasticsearch-index-from-your-dynamodb-table":
    "/searchable#backfill-your-elasticsearch-index-from-your-dynamodb-table",
  "#predictions": "/predictions",
  "#definition-7": "/predictions#definition",
  "#usage-5": "/predictions#usage",
  "#how-it-works": "/predictions#how-it-works",
  "#actions": "/predictions#actions",
  "#action-resources": "/predictions#action-resources",
  "#http": "/http",
  "#definition-8": "/http#definition",
  "#usage-6": "/http#usage",
  "#generates-5": "/http#generates",
};
