#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn spellcheck-diff

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
if [[ $BRANCH_NAME =~ "no branch" ]]; then
  echo "You are rebasing, skipping hook"
  exit 0
fi
 
npx lint-staged
