// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4d997f99-6729-4861-9284-8e37c7e71044",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_H7VKUsI03",
    "aws_user_pools_web_client_id": "32c03s7c1r6c1pet99kif400jr",
    "oauth": {
        "domain": "photoalbumse2e-cypress.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://jetxk3xcjjftjlg3gf2blw3ilu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "photo-albums-e2e3b4b5dc769004b0c88c0195ee05bf4e3-cypress",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_content_delivery_bucket": "photo-albums-e2e-20191008125011-hostingbucket-cypress",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2gspbyrih2751.cloudfront.net",
    "predictions": {
        "identify": {
            "identifyLabels": {
                "proxy": false,
                "region": "us-east-1",
                "defaults": {
                    "type": "LABELS"
                }
            }
        }
    }
};


export default awsmobile;
